SELECT D.DEPT_CODE, D.DEPT_NAMEK, E.EMP_NO, E.EMP_NAMEK, E.EMP_NAMEC, E.EMP_NAMEE, L.LINE_NAME,
       CO.CODE_NAME JIKKUB, E.ENTER_DATE, DECODE(E.SEX_DIS,'1','남자','2','여자','ERROR') SEX_DIS, 
       E.BIRTHDAY, E.BIRTHDAY_GUBUN, E.TEL_NO_1, E.TEL_NO_2, E.ADDRESS, E.PAYMENT_HOUR, E.BANK_NO
FROM EMPM E, DEPTM D, LINEM L, ETC2 CO
WHERE E.DEPT_CODE = D.DEPT_CODE (+) AND E.LINE_CODE = L.LINE_CODE (+)
      AND E.DEPT_CODE = L.DEPT_CODE (+) AND '10' = CO.CODE_TYPE
      AND TRIM(E.JIKKUB) = CO.CODE_CODE AND E.GUBUN = '0' AND E.EMP_NO = '{employee_id}'
ORDER BY E.DEPT_CODE, E.EMP_NO, E.LINE_CODE